export const facts: string[] = [
  'Tyrannosaurus rex had teeth up to 8 inches long, but they were shaped like bananas rather than sharp knives.',
  'The smallest dinosaur ever discovered was Microraptor, which was only about the size of a crow.',
  'Dinosaurs lived on Earth for over 165 million years, far longer than humans have existed.',
  'The largest dinosaur, Argentinosaurus, could grow up to 115 feet long and weigh as much as 12 elephants.',
  'Some dinosaurs, like Therizinosaurus, had claws that were over 3 feet long but were actually herbivores.',
  'Dinosaurs had feathers! Many species, especially theropods, had colorful plumage similar to modern birds.',
  'The Stegosaurus had a brain the size of a walnut, despite being as large as a school bus.',
  'Velociraptors were actually only about the size of a turkey, much smaller than depicted in movies.',
  'Dinosaurs could not roar like in the movies - they likely made sounds more similar to birds or crocodiles.',
  "The name 'dinosaur' means 'terrible lizard' in Greek, though dinosaurs were not actually lizards.",
  'Some dinosaurs, like the Maiasaura, are believed to have cared for their young in nests, showing complex social behavior.',
  'Non-avian maniraptoran dinosaurs (like Velociraptor and its kin) possessed uncinate processes on their ribs—bony projections similar to those in modern diving birds—which enhanced chest-pumping efficiency and indicate they had high-capacity, bird-like respiratory systems. These structures imply sustained, aerobic activity and support the idea that these dinosaurs were far more active—and possibly warm-blooded—than cold-blooded reptiles.',
  'The first dinosaur fossils were scientifically described in the early 19th century, but many ancient cultures discovered dinosaur bones and interpreted them as the remains of dragons or mythical creatures.',
];
